import './globals.scss';
import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';
import Link from 'next/link';
import LogoutButton from './(auth)/api/logout/LogoutButton';

const plex = IBM_Plex_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="wrapper">
      <body className={plex.className}>
        <header>
          <nav>
            <Link href="/zoom">Zoom</Link>
            <Link href="/">Home</Link>
            <Link href="/register">Register</Link>
            <Link href="/login">Login</Link>
            <LogoutButton />
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
